# address-service.yml

spring:
  application:
    name: address-service

  datasource:
    url: jdbc:h2:mem:addressdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      springframework:
        cloud: DEBUG
      hibernate: INFO

server:
  port: 0 # Dinamik port tahsisi yapar, Config Server'dan alındığında ayarlanır.

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
