# config-repo/address-service.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/addressdb
    username: user
    password: password
logging:
  level:
    root: INFO
    com.example.addressservice: DEBUG
